// import 'dart:convert';
import 'dart:io';
import 'package:project/models/words.dart';
import 'package:project/pages/admin/admin_page.dart';
import 'package:project/pages/admin/words/view_all_words.dart';
import 'package:project/services/menu_service.dart';
import 'package:project/services/navigator_service.dart';
import 'package:project/services/words_network_service.dart';

class AddWordPage extends Menu {
  static const String id = "add_words_page";

  late List<Words> listOfWords = <Words>[];

  @override
  Future<void> build() async {
    await getWordsFromAdmin();

    print('1. View all words');
    print('2. Return to the main page');
    String input = stdin.readLineSync()!;
    if (input == '1' || input == "2") {
      switch (input) {
        case "1":
          await Navigator.push(ViewAllWords());
          break;
        case "2":
          await Navigator.pop();
          break;
      }
    } else {
      print('Invalid Input');
      await build();
    }
  }

  Future<void> getWordsFromAdmin() async {
    stdout.write('Enter the number of words you want to add: ');

    try {
      int numberOfWords = int.parse(stdin.readLineSync()!);

      for (var i = 0; i < numberOfWords; i++) {
        print('\nEnter the details of word ${i + 1} : ');
        stdout.write('Word: ');
        String word = stdin.readLineSync()!;

        stdout.write('Translation: ');
        String translation = stdin.readLineSync()!;

        stdout.write('Description: ');
        String description = stdin.readLineSync()!;

        // Note: id and time will be generated by the mock API
        // numOfWord is generated sequentially
        listOfWords.add(Words(
          numOfWord: (i + 1).toString(),
          word: word,
          translation: translation,
          description: description,
        ));
      }

      // Post data to the API
      for (var word in listOfWords) {
        await NetworkService.postData(word);
      }

      print('Words added successfully!');
    } catch (e) {
      print('Invalid input: $e');
    }
  }
}
